### ISSUE TITLE
class cast exception in errorprone plugin

### ISSUE THREAD

**Issue by bavardage** [palantir/gradle-baseline#1097]
## What happened?

class cast exception in errorprone baseline plugin:

```
MyClass.java:191: An unhandled exception was thrown by the Error Prone static analysis plugin.
ERROR: An unhandled exception was thrown by the Error Prone static analysis plugin.
            return () -> {
                   ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.4
     BugPattern: GradleCacheableTaskAction
     Stack Trace:
     java.lang.ClassCastException: class com.sun.tools.javac.tree.JCTree$JCReturn cannot be cast to class com.sun.source.tree.ExpressionTree (com.sun.tools.javac.tree.JCTree$JCReturn and com.sun.source.tree.ExpressionTree are in module jdk.compiler of loader 'app')
  	at com.google.errorprone.matchers.Matchers.lambda$parentNode$13960f3f$1(Matchers.java:369)
  	at com.google.errorprone.matchers.Matchers.lambda$allOf$93cd24cb$1(Matchers.java:127)
  	at com.palantir.baseline.errorprone.GradleCacheableTaskAction.matchLambdaExpression(GradleCacheableTaskAction.java:54)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitLambdaExpression(ErrorProneScanner.java:699)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitLambdaExpression(ErrorProneScanner.java:152)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1815)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
```

## What did you want to happen?
The errorprone check to run without throwing an exception.

**Comment by iamdanfox** [comment]
This seems like you upgraded to error-prone 2.3.4 before you upgraded baseline itself? We fixed this here https://github.com/palantir/gradle-baseline/pull/1083

**Comment by bavardage** [comment]
yes you're correct - closing...
