### ISSUE TITLE
BaselineExactDependencies should filter for only jar artifacts

### ISSUE THREAD

**Issue by gatesn** [palantir/gradle-baseline#594]
We use the jar analyzer, meaning it breaks when taking a dependency on a pom file for example

**Comment by robert3005** [comment]
This manifests in 
```
Caused by: java.lang.IllegalArgumentException: Cannot accept visitor on URL: file:/Users/robertk/.gradle/caches/modules-2/files-2.1/org.apache.spark/spark-dist_2.11-hadoop-palantir/3.0.0-palantir.32/5413978ef8b201b92ba5b6514d8d9167a778d9e3/spark-dist_2.11-hadoop-palantir-3.0.0-palantir.32.pom
        at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.accept(ClassFileVisitorUtils.java:75)
        at org.apache.maven.shared.dependency.analyzer.DefaultClassAnalyzer.analyze(DefaultClassAnalyzer.java:48)
        at com.palantir.baseline.plugins.BaselineExactDependencies$Indexes.lambda$populateIndexes$2(BaselineExactDependencies.java:106)
        at com.palantir.baseline.plugins.BaselineExactDependencies$Indexes.populateIndexes(BaselineExactDependencies.java:103)
        at com.palantir.baseline.tasks.CheckUnusedDependenciesTask.checkUnusedDependencies(CheckUnusedDependenciesTask.java:67)
```
